# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=8080

# ===============================
# CONFIGURACIÓN DE POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/npc_db
spring.datasource.username=postgres
# SUSTITUYE "admin" POR LA CONTRASEÑA QUE PUSISTE AL INSTALAR POSTGRESQL:
spring.datasource.password=admin

# ===============================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===============================
# Esto hace la magia: crea las tablas automáticamente en npc_db si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true